### PR TITLE
Fix overlapping snake part rendering & snake length display

### LINKED ISSUE #69: Snake lengths are incorrect on first two turns.
On turn 1 all snakes show length [1], and on turn 2 all snakes show length [2]. This is technically incorrect, as all snakes are length[3] at the start, they're just stacked on a single square.

After turn [3] they correctly display [3] until they eat food.

**Expected Behaviour:** Length should always be the number of body coordinates provided in the game state json.

### LINKED ISSUE #70: Snake rendering after running into itself still incorrect
Found another corner case that i have not observed before. The behavior is still way better than what we had before, but a bug is a bug.

In the screenshot the part right above the head should be a straight piece facing down instead of a corner piece.

https://play.battlesnake.com/g/588a33a2-208e-43c6-aa76-5e559d871f66
Screenshot from 2019-12-05 11-13-13

I will have a look at what's causing it later.

It seems like a good idea to extend unit tests for every situation we encounter like this to verify no further regressions. It seems however like the part directions are set correctly and the corner detection is messing up which is currently untested as the functions a in local module scope. Maybe we should lift them out into their own util to test them.

### PR DESCRIPTION
**Pull request by hanneskuettner**
This fixes #70 and due to the new approach of keeping the full snake body in the state also fixes #69.

This change renders overlapped snake parts slightly transparent but still visible and fixes all previous render problems.

- Instead of removing overlapping snake parts introduce the isOverlapped flag for overlapped parts
- Introduce effectiveSpace in snake state for correct turn 1 rendering
- Adjust unit tests to accept new state format (Only add new variables)
- Add additional snake part to self-collision test as API sends that part as well

image
image
image

### CODE REVIEW

**Comment by bvanvugt** [comment]
@hanneskuettner thanks for putting this together - can you help me understand the first screenshot? looks like the head is rendered in the wrong direction, or am I misinterpreting that?

**Comment by hanneskuettner** [comment]
The snake is moving up into it's on body. It snaked (ha, get it) down, then to the right and back up on the left side of it's body.

**Comment by bvanvugt** [comment]
Ohhhhhh I thought it was colliding from the right. Makes sense :)

**Comment by hanneskuettner** [comment]
Perfect! :)
You can check out #70 for the game id to verify.

**Pull request merged**
