### PR TITLE
Fix rendering for snakes of length 2

### LINKED ISSUE #65: Snake Bodies Not Rendering Correctly on Turn 2
Screenshot 2019-11-27 11 45 03

Confirmed this is a new bug, as of version 0.0.3 of the board. Suspect it's related to https://github.com/battlesnakeio/board/pull/61 from @hanneskuettner

### PR DESCRIPTION
**Pull request by hanneskuettner**
Fixes #65, caused by #61.

### CODE REVIEW

**Comment by brandonb927** [comment]
This is great and I would love to review the changes here! Unfortunately due to the amount of time I can commit to Battlesnake during the week, I would really appreciate unit tests with changes like this in order for me to feel confident with changes making their way into the Board. I know there's already some that exist [here](https://github.com/battlesnakeio/board/blob/master/src/utils/game-state.test.js).

**Comment by hanneskuettner** [comment]
Any idea how to properly test changes like this which in its nature should be purely visual?

I mean we could test the resulting svg for the correct elements with the correct values, but every change to the visuals would probably result in changes in the created svg and would require adjusting of the unit test which would make them non-sensical, no?

I am actually curious how one could properly test visual output of svgs cause I've never unit tested that before. Maybe rendering to a canvas and comparing output with predefined images?

**Comment by bvanvugt** [comment]
Thanks @hanneskuettner! Agree tests are difficult here. @brandonb927 don't worry we've verified on this side and are happy with this change :)

**Comment by brandonb927** [comment]
@hanneskuettner maybe not testing the visual elements but at least unit testing the functions that were added in this change. I trust @bvanvugt judgement though!

**Pull request merged**
