### PR TITLE
Remove white borders from snake rendering

### PR DESCRIPTION
**Pull request by hanneskuettner**
On some zoom levels the snake body parts had white borders in-between.

This was caused by browser internal floating point imprecisions and sub-pixel alignment.

The problem was solved by extending all parts beyond their respective cell and overlapping them.
This way the parts are draw twice with an overlap and we don't rely on the browser doing the rounding correct. 
For the straight body parts I extended their length and updated their position and for the L-shaped corners I updated the shape itself.

The only "regression": I had to move the tail parts to be drawn inside the cell instead of being closer to the rest of the body. If this is not desired I will improve my implementation to respect the previous positioning.  Personally, I don't mind it and it's prettier than having to deal with the white borders

### CODE REVIEW

**Comment by colinjfw** [comment]
Wow thanks @hanneskuettner, this has been annoying me for quite a while!

**Comment by hanneskuettner** [comment]
Sure thing!

Just make sure to visually verify my results (I have done that, but maybe I missed something) and decide whether it's okay for the tail piece to be on a full tile.

**Comment by bvanvugt** [comment]
@hanneskuettner this is great, thanks!

I want to make sure I understand the change in tail positioning, any chance you can provide some screenshots showing the change?

**Comment by hanneskuettner** [comment]
Previous:
image

Now:
image

The change is due to extending the shape to a full blow corner and with overlaps on both sides. I'm sure I can add some special case handling for cutting of the additional overlap on the second to last piece, but this is what I've got for now :)

**Comment by bvanvugt** [comment]
Perfect, that's what I was hoping you meant. That's a change we've been wanting to make as well :)

I'm going to merge this and hopefully deploy in the next couple days.

**Pull request merged**
