### PR TITLE
[Issue 198] Support rounded-corner snake body parts

### PR DESCRIPTION
**Pull request by nbw**
# Summary

Rounded corners for issue [198](https://github.com/battlesnakeio/roadmap/issues/198).

screenshot 2019-02-10 13 17 30

**Note**: There is an unresolved issue of small gaps between body parts. I've tried a number of solutions with nothing really working well. The lines also appear/disappear depending on the browser zoom. Example:

screenshot 2019-02-10 13 17 14

### CODE REVIEW

**Comment by brandonb927** [comment]
@nbw This is great! I just pulled it down and ran my snake through it and notice this issue:
image

**Comment by nbw** [comment]
@brandonb927 when you say 'at the corners:" do you mean the corner of the grid?

**Comment by brandonb927** [comment]
Yes at each corner of the grid

**Comment by nbw** [comment]
screenshot 2019-02-12 19 25 37

It works!

**Pull request merged**
