### PR TITLE
Convert to one full screen svg

### PR DESCRIPTION
**Pull request by graeme-hill**
Make into one svg that fills the available space and switch to horizontal layout to better use likely aspect ratios. Instead of this:

```
 _______________   _______________   _______________
| Snake 1       | | Snake 2       | | Snake 3       |
| |--------|    | | |-----|       | | |----------|  |
 ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾   ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾   ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾

 ____________________________________________________
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                          ----->                    |
|                                   |                |
|                                   |                |
|                                   |                |
|                      ^            |                |
|                      |            v                |
|                      |                             |
|                      |                             |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
 ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
```

We now have this:

```
 ____________________________________________________     
|                                                    |      _______________ 
|                                                    |     | Snake 1       |
|                                                    |     | |--------|    |
|                                                    |      ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾ 
|                                                    |      _______________ 
|                    -------->                       |     | Snake 2       |
|                                 |                  |     | |------|      |
|                                 |                  |      ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾ 
|                                 |                  |      _______________ 
|                                 v                  |     | Snake 3       |
|                                                    |     | |----------|  |
|                   ^                                |      ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾ 
|                   |                                |
|                   |                                |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
|                                                    |
 ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
```

### CODE REVIEW

**Comment by will-swu** [comment]
Nice ascii art

**Comment by brandonb927** [comment]
@graeme-hill I think one comment @bvanvugt made early on was possibly separating those two components and just having the board as "the board" and having a separate "scoreboard" component served by the board project. Obviously not something to jump on now, but something possibly for the future?

**Comment by brandonb927** [comment]
@graeme-hill I'm seeing an issue with this when testing it out where snake segments contain 1px gaps between them
image

**Comment by brandonb927** [comment]
I'm also seeing what appears to be a performance regression when running 4 or more snakes at once.

**Comment by graeme-hill** [comment]
Ok I have some updates finally @brandonb927!

I have not merged in your branch because when I tested it I was getting a bunch of issues with window resizing. Instead, I have just implemented the coloured health bar like you did for now. If we merge this I'd be happy to take ownership of making sure it sizes properly inside play when the iframe changes size.

Things I've changed:

1. Fixed tiny sub-pixel gaps that were appearing between snake segments on some zoom levels (fixed for me at least, hope it works for everyone :crossed_fingers:)
2. Health bar has same colour as snake
3. Improved performance a bit with better keys in loops allowing react to reuse stuff better.
4. Added a log message that gives you some timing information after a game is finished rendering. It looks like this:

```201 turns in 4382 milliseconds - 21.8009/turn```

^^^ I had to remove the render speed cap in engine-client.js temporarily to get it this fast. Normally it won't go faster than 30ms/turn. On my slow laptop I get about 60ms/turn in a game with 8 snakes which is the maximum we support.

Normal behaviour in battlesnake 2018 was 200ms/turn since we were playing them live. By comparison 60ms is pretty good. If it still feels slow for you let me know what the timing message says in the console.

**Comment by brandonb927** [comment]
@graeme-hill 🙌 this is great, I'll play with it tonight and let you know!

**Pull request merged**
